clear; close; clc;

data = readtable('debug_data.csv'); % Read the data

figure;

plot(data.time, data.x_bb, '-+',...
    data.time, data.y_bb, '-o',...
    data.time, data.w_bb, '-*',...
    data.time, data.h_bb, '-.',...
    data.time, data.v_xr.*10, '-^',...
    data.time, data.v_yr.*10, '->',...
    data.time, data.v_zr.*10, '-<',...
    data.time, data.yawrate.*10,  '-p',...
    data.time, data.f_u, '-x',...
    data.time, data.f_v, '-s',...
    data.time, data.f_delta, '-d',...
    data.time, data.delta_f_u_psi, '-^',...
    data.time, data.delta_f_u_y, '->',...
    data.time, data.delta_f_v_z, '-^',...
    data.time, data.delta_f_delta_x, '-p',...
    data.time, data.delta_x_tme, '-h',...
    data.time, data.delta_y_tme, '-+',...
    data.time, data.delta_z_tme, '-o',...
    data.time, data.delta_psi_tme, '-*',...
    data.time, data.prev_delta_x_tme, '-.',...
    data.time, data.prev_delta_y_tme, '-x',...
    data.time, data.prev_delta_z_tme, '-s',...
    data.time, data.prev_delta_psi_tme, '-d')

legend('x_{bb}',...
    'y_{bb}',...
    'w_{bb}',...
    'h_{bb}',...
    'v_{xr}',...
    'v_{yr}',...
    'v_{zr}',...
    'v_{yawrate}',...
    'f_u',...
    'f_v',...
    'f_{\Delta}',...
    '\Delta f_{u\psi}',...
    '\Delta f_{uy}',...
    '\Delta f_{vz}',...
    '\Delta f_{\Delta x}',...
    '\Delta x_{tme}',...
    '\Delta y_{tme}',...
    '\Delta z_{tme}',...
    '\Delta \psi_{tme}',...
    'prev \Delta_{xtme}',...
    'prev \Delta_{ytme}',...
    'prev \Delta_{zt,e}',...
    'prev \Delta_{\psi tme}')

figure;

plot(data.time, data.x_bb, '-+',...
    data.time, data.y_bb, '-o',...
    data.time, data.w_bb, '-*',...
    data.time, data.h_bb, '-.',...
    data.time, data.v_xr.*100, '-^',...
    data.time, data.v_yr.*100, '->',...
    data.time, data.v_zr.*100, '-<',...
    data.time, data.yawrate.*100,  '-p',...
    data.time, data.roll_angle.*100, '-^',...
    data.time, data.pitch_angle.*100, '->',...
    data.time, data.yaw_angle.*10, '-<',...
    data.time, data.delta_f_delta_x.*100, '-p')

legend('x_{bb}',...
    'y_{bb}',...
    'w_{bb}',...
    'h_{bb}',...
    'v_{xr} * 100',...
    'v_{yr} * 100',...
    'v_{zr} * 100',...
    'v_{yawrate} * 100',...
    'roll angle * 100',...
    'pitch angle * 100',...
    'yaw angle * 10',...
    'delta_{f\Delta_x} * 100')